#!/usr/bin/env bash
# Regenerate requirements.txt from poetry.lock (Vercel reads this file).
set -euo pipefail
cd "$(dirname "$0")/.."

HEADER='# Generated by scripts/export-requirements.sh from poetry.lock. Do not edit by hand.
'

poetry export \
  -f requirements.txt \
  --without-hashes \
  --output requirements.txt.tmp

printf '%s' "$HEADER" > requirements.txt
cat requirements.txt.tmp >> requirements.txt
rm requirements.txt.tmp
